FROM node:9.9-alpine

# React libraries
WORKDIR /app/frontend
COPY package.json yarn.lock /app/frontend/
RUN yarn --frozen-lockfile --production

# React build (Production-ish)
COPY . /app/frontend
ARG REACT_APP_API_HOST
ARG PUBLIC_URL
RUN yarn build

FROM nginx:alpine
COPY etc/nginx-site.conf /etc/nginx/conf.d/default.conf
COPY --from=0 /app/frontend/build /usr/share/nginx/html
