FROM node:9.9-alpine

# React libraries
WORKDIR /app/frontend
COPY package.json yarn.lock /app/frontend/
RUN yarn --frozen-lockfile --production

# React build (Production-ish)
COPY . /app/frontend
RUN yarn build

FROM nginx:alpine
COPY --from=0 /app/frontend/build /usr/share/nginx/html
