version: "3"

services:
    frontend:
        build:
            context: frontend
        container_name: "frontend"
        image: frontend
        tmpfs:
            - /tmp
        environment:
            - PORT=80
    rustend:
        build:
            context: rustend
        container_name: "rustend"
        image: rustend
        ports:
            - "8000:80"
        links:
            - db
        environment:
            DATABASE_URL: postgres://postgres:supersecretpassword2@db/rustydb
        tmpfs:
            - /tmp
    db:
        image: "postgres:9"
        expose:
            - 5432
        volumes:
            - pg-data:/var/lib/postgresql/data/pgdata
        environment:
            POSTGRES_PASSWORD: supersecretpassword2
            PGDATA: /var/lib/postgresql/data/pgdata
volumes:
    pg-data:
