version: "3"

services:
    frontend:
        build:
            context: frontend
        container_name: "frontend"
        image: frontend
        links:
            - rustend
        tmpfs:
            - /tmp
        environment:
            PORT: 80
            HOST: 0.0.0.0
            REACT_APP_API_HOST: http://localhost:8000
    rustend:
        build:
            context: rustend
        container_name: "rustend"
        image: rustend
        ports:
            - "8000:80"
            - "3012:3012"
        links:
            - db
        environment:
            DATABASE_URL: postgres://postgres:supersecretpassword2@db/rustydb
            CARGO_INCREMENTAL: 1
            FRONTEND_HOST: http://localhost:3000
        tmpfs:
            - /tmp
    db:
        image: "postgres:9"
        expose:
            - 5432
        volumes:
            - pg-data:/var/lib/postgresql/data/pgdata
        environment:
            POSTGRES_PASSWORD: supersecretpassword2
            PGDATA: /var/lib/postgresql/data/pgdata
            POSTGRES_DB: rustydb
volumes:
    pg-data:
